src/MyGymApp.UI/Models/WorkoutRecordViewModels/AddWorkoutRecordViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyGymApp.UI.Models.WorkoutRecordViewModels
{
    public class AddWorkoutRecordViewModel
    {
        [Required]
        [Display(Name = "Activity Name")]
        public string ActivityName { get; set; }
        public int Duration { get; set; }
        public int Sets { get; set; }
        public int Reps { get; set; }
        [Required]
        public int[] MusclesListIds { get; set; }
        public MultiSelectList MusclesList { get; set; }
    }
}

src/MyGymApp.UI/Models/WorkoutSessionViewModels/WorkoutSessionCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyGymApp.DataAccess.Models;
using MyGymApp.UI.Models.WorkoutRecordViewModels;

namespace MyGymApp.UI.Models.WorkoutSessionViewModels
{
    public class WorkoutSessionCreateViewModel
    {
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime Date { get; set; }
        public List<AddWorkoutRecordViewModel> WorkoutRecords { get; set; }
    }
}

src/MyGymApp.UI/Models/WorkoutSessionViewModels/WorkoutSessionIndexViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyGymApp.UI.Models.WorkoutSessionViewModels
{
    public class WorkoutSessionIndexViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }       
        [DisplayFormat(DataFormatString = "{0:d}")]
        public DateTime Date { get; set; }
        [Display(Name = "Workout Records")]
        public int WorkoutRecords { get; set; }
    }
}

src/MyGymApp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyGymApp.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/MyGymApp.UI/Controllers/WorkoutSessionController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGymApp.DataAccess.Models;
using MyGymApp.Services;
using MyGymApp.UI.Models.WorkoutSessionViewModels;
using MyGymApp.Commands.WorkoutSession;

namespace MyGymApp.UI.Controllers
{
    public class WorkoutSessionController : Controller
    {
        private readonly MyGymAppDbContext _context;
        private readonly WorkoutSessionApplicationService _workoutSessionService;

        public WorkoutSessionController(MyGymAppDbContext context, WorkoutSessionApplicationService workoutSessionService)
        {
            _context = context;
            _workoutSessionService = workoutSessionService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var results = _context.WorkoutSessions.Select(ws => new WorkoutSessionIndexViewModel
            {
                Id = ws.WorkoutSessionId,
                Description = ws.Description,
                Date = ws.Date,
                WorkoutRecords = ws.WorkoutRecords.Count
            }).OrderByDescending(d => d.Date).ToList();
            return View(results);
        }

        [HttpGet]
        [Route("MyWorkoutSessions/Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetMuscles()
        {
            var result = _context.Muscles.ToList();
            if (!result.Any())
            {
                return NotFound();
            }
            return Ok(result);
        }

        [HttpPost]
        [Route("MyWorkoutSessions/Create")]
        public async Task<IActionResult> Create(WorkoutSessionCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var command = new CreateWorkoutSessionCommand
            {
                Description = model.Description,
                Date = model.Date,
                WorkoutRecords = model.WorkoutRecords.Select(wr => new WorkoutRecord()
                {
                    ActivityName = wr.ActivityName,
                    DurationInMinutes = wr.Duration,
                    NumberOfReps = wr.Reps,
                    NumberOfSets = wr.Sets,
                    MusclesTargeted = wr.MusclesListIds.Select(w => new WorkoutRecordMuscle
                    {
                        MuscleId = w
                    }).ToList()
                }).ToList()
            };
            await _workoutSessionService.AddWorkoutSession(command);
            return RedirectToAction("Index");
        }
    }
}

src/MyGymApp.UI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/MyGymApp.UI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>
    Juan Andres Rondon<br />
    <abbr title="Phone">P:</abbr>
    0416966751
</p>

<address>
    <strong>Email:</strong> <a href="mailto:juanrondonc@outlook.com">juanrondonc@outlook.com</a>
</address>

src/MyGymApp.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container">
    <div class="jumbotron">
        <h1>MyGymTracker</h1>
        <p>This is a simple application that will help you keep track of all your gym acitvity.</p>
        <img src="~/images/gym_background.jpg" class="img-responsive img-rounded" alt="image"/>

    </div>


</div>

src/MyGymApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyGymTracker</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

        <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.common-bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.bootstrap.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.common-bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/kendo-ui-core/styles/kendo.bootstrap.min.css" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyGym-Tracker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="WorkoutSession" asp-action="Index">Workouts</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MyGymTracker</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/kendo-ui-core/js/kendo.ui.core.min.js"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/kendo-ui-core/js/kendo.ui.core.min.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/MyGymApp.UI/Views/WorkoutSession/Create.cshtml
@model MyGymApp.UI.Models.WorkoutSessionViewModels.WorkoutSessionCreateViewModel

@{
    ViewData["Title"] = "Create";
}
<h3>Create workout Session</h3>
<form asp-action="Create" id="form">
    <div class="container">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    <span class="glyphicon glyphicon-file">
                                    </span> Details
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label asp-for="Description" class="col-md-2 control-label"></label>
                                        <div class="col-md-10">
                                            <textarea asp-for="Description" rows="4" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Date" class="col-md-2 control-label"></label>
                                        <div class="col-md-10">
                                            <input asp-for="Date" class="form-control" id="datePicker" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                    <span class="glyphicon glyphicon-plus-sign">
                                    </span> Activities
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse">
                            <div class="panel-body">
                                <button id="add-workout-btn" type="button" class="btn btn-primary">Add workout</button>
                                <div id="templateContent"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/handlebars/handlebars.js"></script>
    @*Handlebars template*@
    <script id="entry-template" type="text/x-handlebars-template">
        <div class="form form-inline">
            <div class="form-group" style="margin: 5px;">
                <input name="WorkoutRecords[{{i}}].ActivityName" placeholder="Activity" class="form-control activity" style="width: 300px;" />

            </div>
            <div class="form-group input-group">
                <input type="number" min="0" name="WorkoutRecords[{{i}}].Duration" class="form-control duration" value="0" style="width: 70px;">
                <span class="input-group-addon">Min</span>
            </div>
            <div class="form-group input-group">
                <input type="number" min="0" name="WorkoutRecords[{{i}}].Sets" class="form-control sets" value="0" style="width: 70px;">
                <span class="input-group-addon">Sets</span>
            </div>
            <div class="form-group input-group">
                <input type="number" min="0" name="WorkoutRecords[{{i}}].Reps" class="form-control reps" value="0" style="width: 70px;">
                <span class="input-group-addon">Reps</span>
            </div>
            <div class="form-group">
                <select multiple="multiple" id="musclesList{{i}}" class="muscleList" name="WorkoutRecords[{{i}}].MusclesListIds" style="width: 300px;"></select>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-danger">Remove</button>
            </div>
        </div>
    </script>

    <script>
        (function () {
            var source = $("#entry-template").html();
            var template = Handlebars.compile(source);
            var pos = -1;
            $(document).ready(function () {
                $("#datePicker").kendoDatePicker({
                    value: new Date(),
                    min: new Date(),
                    format: "dd/MM/yyyy"
                });

                $("#add-workout-btn").click(function () {
                    var data = { i: ++pos };
                    var html = template(data);
                    $("#templateContent").append(html);

                    $("#musclesList" + pos).kendoMultiSelect({
                        placeholder: "Select Targeted Muscles ...",
                        dataTextField: "name",
                        dataValueField: "muscleId",
                        autoBind: false,
                        dataSource: {
                            transport: {
                                read: {
                                    url: "/WorkoutSession/getmuscles",
                                    contentType: "application/json; charset=utf-8",
                                    type: "GET",
                                    dataType: "json"
                                }
                            }
                        }
                    });
                });
                $(document).on('click', '.btn-danger', function () {
                    var p = 0;
                    $(this).closest('.form-inline').remove();
                    $('.activity').each(function (index) {
                        $(this).attr('name', 'WorkoutRecords[' + index + '].ActivityName');
                    });
                    $('.duration').each(function (index) {
                        $(this).attr('name', 'WorkoutRecords[' + index + '].Duration');
                    });
                    $('.sets').each(function (index) {
                        $(this).attr('name', 'WorkoutRecords[' + index + '].Sets');
                    });
                    $('.reps').each(function (index) {
                        $(this).attr('name', 'WorkoutRecords[' + index + '].Reps');
                    });
                    $('select.muscleList').each(function (index) {
                        $(this).attr('name', 'WorkoutRecords[' + index + '].MusclesListIds');
                        $(this).attr('id', 'musclesList' + index);
                        p++;
                    });
                    pos = p - 1;
                });
            });
        })();
    </script>
}

src/MyGymApp.UI/Views/WorkoutSession/Index.cshtml
@model IEnumerable<MyGymApp.UI.Models.WorkoutSessionViewModels.WorkoutSessionIndexViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Workout Sessions</h2>

<p>
    <a asp-action="Create">Create New Workout</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkoutRecords)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <span class="badge">@item.WorkoutRecords</span><a href="#"> Activities </a>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>